export const strings = {
  EMAIL: 'Email',
  SYNC: 'Sync',
  SELECT_COUNTRY: 'Select Country',
  SELECT_STATE: 'Select State',
  SELECT_CITY: 'Select City',
  COUNTRY: 'Country',
  STATE: 'State',
  CITY: 'City',
  CREATE_EVENT: 'Create Event',
  LOG_OUT: 'Logout',
  SIGN_UP: 'Sign Up',
  LOGIN: 'Login',
  NAME_OF_THE_EVENT: 'Name of the event:',
  DATE: 'Date:',
  TIME: 'Time:',
  ENTER_LOCATION: 'Name:',
  IMAGES: 'Images',
  UPLOAD_IMAGES: 'Upload Images',
  NUMBER_OF_ATTENDEES: 'Number of Attendees:',
  DESCRIPTION: 'Description:',
  BACK_TO_LOGIN: 'Back to login',
  FORGOT_PASSWORD: 'Forgot Password',
  FORGOT_PASSWORD_Q: 'Forgot Password?',
  ENTER_YOUR_EMAIL:
    'Please enter the email address you would like your password reset information sent to',
  REQUEST_RESET_LINK: 'Request reset link',
};
