export const strings = {
  EMAIL: 'Email',
  SYNC: 'Sync',
  LOG_OUT: 'Logout',
  SIGN_UP: 'Sign Up',
  LOGIN: 'Login',
  NAME_OF_THE_EVENT: 'Name of the event:',
  DATE: 'Date:',
  TIME: 'Time:',
  ENTER_LOCATION: 'Name:',
  SELECT_IMAGES: 'Name:',
  NUMBER_OF_ATTENDEES: 'Name:',
  DESCRIPTION: 'Name:',
  BACK_TO_LOGIN: 'Back to login',
  FORGOT_PASSWORD: 'Forgot Password',
  FORGOT_PASSWORD_Q: 'Forgot Password?',
  ENTER_YOUR_EMAIL:
    'Please enter the email address you would like your password reset information sent to',
  REQUEST_RESET_LINK: 'Request reset link',
};
